/**
 * Queen origin catalogs: ISO countries and derived origin regions.
 * Regions are computed from countries — do not store them on queen JSON.
 */

/** ISO 3166-1 alpha-2 country codes used for queen origin. */
export const Country = {
  AD: "AD",
  AR: "AR",
  AT: "AT",
  AU: "AU",
  BB: "BB",
  BE: "BE",
  BO: "BO",
  BR: "BR",
  BS: "BS",
  CA: "CA",
  CH: "CH",
  CL: "CL",
  CM: "CM",
  CN: "CN",
  CO: "CO",
  CR: "CR",
  CU: "CU",
  CZ: "CZ",
  DE: "DE",
  DK: "DK",
  DO: "DO",
  EC: "EC",
  EG: "EG",
  ES: "ES",
  FI: "FI",
  FJ: "FJ",
  FR: "FR",
  GB: "GB",
  GH: "GH",
  GP: "GP",
  GR: "GR",
  GT: "GT",
  GY: "GY",
  HN: "HN",
  HT: "HT",
  HU: "HU",
  ID: "ID",
  IE: "IE",
  IL: "IL",
  IN: "IN",
  IS: "IS",
  IT: "IT",
  JM: "JM",
  JP: "JP",
  KE: "KE",
  KH: "KH",
  KR: "KR",
  LA: "LA",
  LB: "LB",
  LT: "LT",
  LU: "LU",
  LV: "LV",
  MA: "MA",
  MQ: "MQ",
  MX: "MX",
  MY: "MY",
  NG: "NG",
  NI: "NI",
  NL: "NL",
  NO: "NO",
  NZ: "NZ",
  PA: "PA",
  PE: "PE",
  PH: "PH",
  PL: "PL",
  PR: "PR",
  PT: "PT",
  PY: "PY",
  RO: "RO",
  RS: "RS",
  RU: "RU",
  SE: "SE",
  SG: "SG",
  SI: "SI",
  SK: "SK",
  SR: "SR",
  SV: "SV",
  TH: "TH",
  TR: "TR",
  TT: "TT",
  TW: "TW",
  UA: "UA",
  US: "US",
  UY: "UY",
  VE: "VE",
  VN: "VN",
  ZA: "ZA",
} as const;

export type Country = (typeof Country)[keyof typeof Country];

/**
 * Geographic origin groupings for agent filters.
 * `latin_america` excludes Spain/Portugal (`iberia`).
 */
export const OriginRegion = {
  LATIN_AMERICA: "latin_america",
  CARIBBEAN: "caribbean",
  IBERIA: "iberia",
  NORTH_AMERICA: "north_america",
  EUROPE: "europe",
  AFRICA: "africa",
  ASIA: "asia",
  OCEANIA: "oceania",
} as const;

export type OriginRegion =
  (typeof OriginRegion)[keyof typeof OriginRegion];

export const COUNTRY_ORIGIN_REGIONS = {
  AD: ["europe", "iberia"],
  AR: ["latin_america"],
  AT: ["europe"],
  AU: ["oceania"],
  BB: ["caribbean"],
  BE: ["europe"],
  BO: ["latin_america"],
  BR: ["latin_america"],
  BS: ["caribbean"],
  CA: ["north_america"],
  CH: ["europe"],
  CL: ["latin_america"],
  CM: ["africa"],
  CN: ["asia"],
  CO: ["latin_america"],
  CR: ["latin_america"],
  CU: ["latin_america", "caribbean"],
  CZ: ["europe"],
  DE: ["europe"],
  DK: ["europe"],
  DO: ["latin_america", "caribbean"],
  EC: ["latin_america"],
  EG: ["africa"],
  ES: ["europe", "iberia"],
  FI: ["europe"],
  FJ: ["oceania"],
  FR: ["europe"],
  GB: ["europe"],
  GH: ["africa"],
  GP: ["caribbean"],
  GR: ["europe"],
  GT: ["latin_america"],
  GY: ["latin_america"],
  HN: ["latin_america"],
  HT: ["caribbean"],
  HU: ["europe"],
  ID: ["asia"],
  IE: ["europe"],
  IL: ["asia"],
  IN: ["asia"],
  IS: ["europe"],
  IT: ["europe"],
  JM: ["caribbean"],
  JP: ["asia"],
  KE: ["africa"],
  KH: ["asia"],
  KR: ["asia"],
  LA: ["asia"],
  LB: ["asia"],
  LT: ["europe"],
  LU: ["europe"],
  LV: ["europe"],
  MA: ["africa"],
  MQ: ["caribbean"],
  MX: ["latin_america", "north_america"],
  MY: ["asia"],
  NG: ["africa"],
  NI: ["latin_america"],
  NL: ["europe"],
  NO: ["europe"],
  NZ: ["oceania"],
  PA: ["latin_america"],
  PE: ["latin_america"],
  PH: ["asia"],
  PL: ["europe"],
  PR: ["latin_america", "caribbean"],
  PT: ["europe", "iberia"],
  PY: ["latin_america"],
  RO: ["europe"],
  RS: ["europe"],
  RU: ["europe"],
  SE: ["europe"],
  SG: ["asia"],
  SI: ["europe"],
  SK: ["europe"],
  SR: ["latin_america"],
  SV: ["latin_america"],
  TH: ["asia"],
  TR: ["asia", "europe"],
  TT: ["caribbean"],
  TW: ["asia"],
  UA: ["europe"],
  US: ["north_america"],
  UY: ["latin_america"],
  VE: ["latin_america"],
  VN: ["asia"],
  ZA: ["africa"],
} as const satisfies Record<Country, readonly OriginRegion[]>;

export const COUNTRY_LABEL: Record<Country, string> = {
  AD: "Andorra",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BB: "Barbados",
  BE: "Belgium",
  BO: "Bolivia",
  BR: "Brazil",
  BS: "Bahamas",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CZ: "Czechia",
  DE: "Germany",
  DK: "Denmark",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  ES: "Spain",
  FI: "Finland",
  FJ: "Fiji",
  FR: "France",
  GB: "United Kingdom",
  GH: "Ghana",
  GP: "Guadeloupe",
  GR: "Greece",
  GT: "Guatemala",
  GY: "Guyana",
  HN: "Honduras",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  KE: "Kenya",
  KH: "Cambodia",
  KR: "South Korea",
  LA: "Laos",
  LB: "Lebanon",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  MA: "Morocco",
  MQ: "Martinique",
  MX: "Mexico",
  MY: "Malaysia",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  PA: "Panama",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PR: "Puerto Rico",
  PT: "Portugal",
  PY: "Paraguay",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SR: "Suriname",
  SV: "El Salvador",
  TH: "Thailand",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  UA: "Ukraine",
  US: "United States",
  UY: "Uruguay",
  VE: "Venezuela",
  VN: "Vietnam",
  ZA: "South Africa",
};

export const ORIGIN_REGION_LABEL: Record<OriginRegion, string> = {
  latin_america: "Latin America (excludes Spain)",
  caribbean: "Caribbean",
  iberia: "Iberia (Spain, Portugal, Andorra)",
  north_america: "North America",
  europe: "Europe (includes Iberia)",
  africa: "Africa",
  asia: "Asia",
  oceania: "Oceania",
};

export const ORIGIN_REGION_ALIASES: Record<OriginRegion, readonly string[]> = {
  latin_america: [
    "latin america",
    "latam",
    "latina",
    "latinas",
    "latin american",
  ],
  caribbean: ["caribbean", "west indies"],
  iberia: ["iberia", "iberian"],
  north_america: ["north america", "north american"],
  europe: ["europe", "european"],
  africa: ["africa", "african"],
  asia: ["asia", "asian"],
  oceania: ["oceania", "australia", "new zealand", "pacific"],
};

/** Unique origin regions derived from one or more countries. */
export const originRegionsForCountries = (
  countries: readonly Country[],
): OriginRegion[] => {
  const regions = new Set<OriginRegion>();
  for (const country of countries) {
    for (const region of COUNTRY_ORIGIN_REGIONS[country]) {
      regions.add(region);
    }
  }
  return [...regions].sort();
};
